############################################################################
# 以 '#' 开头的是注释。                                                       #
# '='前面的是key，不能修改。                              #
# 更多信息请访问：                                              #
#   http://blog.csdn.net/fesdgasdgasdg/article/details/52325590            #
#   http://download.csdn.net/detail/fesdgasdgasdg/9913744                  #
#   https://github.com/mengzhinan/PhoneScreenMatch                         #
############################################################################
#
# 每次修改配置都需要刷新或重新打开项目，
# 否则无法获取最新的配置参数。
#
#############################################################################
#
# 屏幕匹配的基本 dp 值。将屏幕切割成 [base_dp] 部分。
# 数据类型为双精度。系统默认值为 360。
# 我劝你不要修改这个值，小心！！！！！！！！！ _^_ _
base_dp=360
# 还需要匹配【match_dp】的手机屏幕。
# 如果您有另一个 dp 值。
# 系统默认值为 240,320,384,392,400,410,411,480,533,592,600,640,662,720,768,800,811,820,960,961,1024,1280,1365
match_dp=
# 如果您不想匹配上面的 dp 值。在这里写一些上面的值，用 "," 附加值。
# 例如：811,961,1365
ignore_dp=
# 它们不是 android 模块名称。如果有更多，用 , 符号分割。
# 如果设置，它不会显示在 SelectDialog 中。
# 如果有，请在此处写下并用“,”附加值。
# 例如：testLibrary,commonModule
# 系统默认值为 .gradle、gradle、.idea、build、.git
ignore_module_name=
# 使用valuesdimen.xml文件下的哪个模块做基础文件，
# 并生成的 dimen.xml 文件存储在此模块中？
# 默认值为“应用程序”。
match_module=app
# 使用此插件时不再显示选择对话框。
# 系统屏幕匹配将使用最后选择的模块名称或默认模块名称。
# 您可以给值 true 或 false。默认值为假。
not_show_dialog=false
# 是否要生成默认示例 dimens.xml 文件？
# 在 ...projectNamescreenMatch_example_dimens.xml 的路径中，它不会影响您的项目代码。
# 您可以给值 true 或 false。默认值为假。
not_create_default_dimens=false
# 字体大小是否与DP相同?可能不准确。
# 你可以给值 true 或 false。默认值为true。还需要扩大。
is_match_font_sp=true
# Do you want to create values-wXXXdp folder or values-swXXXdp folder ?
# I suggest you create values-swXXXdp folder,
# because I had a problem when I was working on the horizontal screen adapter.
# values-swXXXdp folder can solve my problem.
# If you want create values-swXXXdp folder, set "create_values_sw_folder=true",
# otherwise set "create_values_sw_folder=true".
# Default values is true.
create_values_sw_folder=true
